package br.feevale.applogistica.database.orm;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import br.feevale.applogistica.database.orm.Motorista;
import br.feevale.applogistica.database.orm.Cliente;
import br.feevale.applogistica.database.orm.Produto;
import br.feevale.applogistica.database.orm.Entrega;

import br.feevale.applogistica.database.orm.MotoristaDao;
import br.feevale.applogistica.database.orm.ClienteDao;
import br.feevale.applogistica.database.orm.ProdutoDao;
import br.feevale.applogistica.database.orm.EntregaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig motoristaDaoConfig;
    private final DaoConfig clienteDaoConfig;
    private final DaoConfig produtoDaoConfig;
    private final DaoConfig entregaDaoConfig;

    private final MotoristaDao motoristaDao;
    private final ClienteDao clienteDao;
    private final ProdutoDao produtoDao;
    private final EntregaDao entregaDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        motoristaDaoConfig = daoConfigMap.get(MotoristaDao.class).clone();
        motoristaDaoConfig.initIdentityScope(type);

        clienteDaoConfig = daoConfigMap.get(ClienteDao.class).clone();
        clienteDaoConfig.initIdentityScope(type);

        produtoDaoConfig = daoConfigMap.get(ProdutoDao.class).clone();
        produtoDaoConfig.initIdentityScope(type);

        entregaDaoConfig = daoConfigMap.get(EntregaDao.class).clone();
        entregaDaoConfig.initIdentityScope(type);

        motoristaDao = new MotoristaDao(motoristaDaoConfig, this);
        clienteDao = new ClienteDao(clienteDaoConfig, this);
        produtoDao = new ProdutoDao(produtoDaoConfig, this);
        entregaDao = new EntregaDao(entregaDaoConfig, this);

        registerDao(Motorista.class, motoristaDao);
        registerDao(Cliente.class, clienteDao);
        registerDao(Produto.class, produtoDao);
        registerDao(Entrega.class, entregaDao);
    }
    
    public void clear() {
        motoristaDaoConfig.getIdentityScope().clear();
        clienteDaoConfig.getIdentityScope().clear();
        produtoDaoConfig.getIdentityScope().clear();
        entregaDaoConfig.getIdentityScope().clear();
    }

    public MotoristaDao getMotoristaDao() {
        return motoristaDao;
    }

    public ClienteDao getClienteDao() {
        return clienteDao;
    }

    public ProdutoDao getProdutoDao() {
        return produtoDao;
    }

    public EntregaDao getEntregaDao() {
        return entregaDao;
    }

}
