package br.feevale.applogistica.database.orm;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import br.feevale.applogistica.database.orm.Motorista;
import br.feevale.applogistica.database.orm.Clientes;
import br.feevale.applogistica.database.orm.Produtos;
import br.feevale.applogistica.database.orm.Entregas;

import br.feevale.applogistica.database.orm.MotoristaDao;
import br.feevale.applogistica.database.orm.ClientesDao;
import br.feevale.applogistica.database.orm.ProdutosDao;
import br.feevale.applogistica.database.orm.EntregasDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig motoristaDaoConfig;
    private final DaoConfig clientesDaoConfig;
    private final DaoConfig produtosDaoConfig;
    private final DaoConfig entregasDaoConfig;

    private final MotoristaDao motoristaDao;
    private final ClientesDao clientesDao;
    private final ProdutosDao produtosDao;
    private final EntregasDao entregasDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        motoristaDaoConfig = daoConfigMap.get(MotoristaDao.class).clone();
        motoristaDaoConfig.initIdentityScope(type);

        clientesDaoConfig = daoConfigMap.get(ClientesDao.class).clone();
        clientesDaoConfig.initIdentityScope(type);

        produtosDaoConfig = daoConfigMap.get(ProdutosDao.class).clone();
        produtosDaoConfig.initIdentityScope(type);

        entregasDaoConfig = daoConfigMap.get(EntregasDao.class).clone();
        entregasDaoConfig.initIdentityScope(type);

        motoristaDao = new MotoristaDao(motoristaDaoConfig, this);
        clientesDao = new ClientesDao(clientesDaoConfig, this);
        produtosDao = new ProdutosDao(produtosDaoConfig, this);
        entregasDao = new EntregasDao(entregasDaoConfig, this);

        registerDao(Motorista.class, motoristaDao);
        registerDao(Clientes.class, clientesDao);
        registerDao(Produtos.class, produtosDao);
        registerDao(Entregas.class, entregasDao);
    }
    
    public void clear() {
        motoristaDaoConfig.getIdentityScope().clear();
        clientesDaoConfig.getIdentityScope().clear();
        produtosDaoConfig.getIdentityScope().clear();
        entregasDaoConfig.getIdentityScope().clear();
    }

    public MotoristaDao getMotoristaDao() {
        return motoristaDao;
    }

    public ClientesDao getClientesDao() {
        return clientesDao;
    }

    public ProdutosDao getProdutosDao() {
        return produtosDao;
    }

    public EntregasDao getEntregasDao() {
        return entregasDao;
    }

}
