package br.feevale.applogistica.database.orm;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTREGAS.
 */
public class Entregas {

    private Long id;
    private Long id_cliente;
    private Long id_motorista;
    private Integer ordem;
    private Integer volumes;
    private String dh_maxima;
    private String gln;
    private String melhor_rota;
    private String nome_contato;
    private String telefone;
    private String dh_entrega;
    private String imagem_documento;
    private String dh_sincronismo;

    public Entregas() {
    }

    public Entregas(Long id) {
        this.id = id;
    }

    public Entregas(Long id, Long id_cliente, Long id_motorista, Integer ordem, Integer volumes, String dh_maxima, String gln, String melhor_rota, String nome_contato, String telefone, String dh_entrega, String imagem_documento, String dh_sincronismo) {
        this.id = id;
        this.id_cliente = id_cliente;
        this.id_motorista = id_motorista;
        this.ordem = ordem;
        this.volumes = volumes;
        this.dh_maxima = dh_maxima;
        this.gln = gln;
        this.melhor_rota = melhor_rota;
        this.nome_contato = nome_contato;
        this.telefone = telefone;
        this.dh_entrega = dh_entrega;
        this.imagem_documento = imagem_documento;
        this.dh_sincronismo = dh_sincronismo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getId_cliente() {
        return id_cliente;
    }

    public void setId_cliente(Long id_cliente) {
        this.id_cliente = id_cliente;
    }

    public Long getId_motorista() {
        return id_motorista;
    }

    public void setId_motorista(Long id_motorista) {
        this.id_motorista = id_motorista;
    }

    public Integer getOrdem() {
        return ordem;
    }

    public void setOrdem(Integer ordem) {
        this.ordem = ordem;
    }

    public Integer getVolumes() {
        return volumes;
    }

    public void setVolumes(Integer volumes) {
        this.volumes = volumes;
    }

    public String getDh_maxima() {
        return dh_maxima;
    }

    public void setDh_maxima(String dh_maxima) {
        this.dh_maxima = dh_maxima;
    }

    public String getGln() {
        return gln;
    }

    public void setGln(String gln) {
        this.gln = gln;
    }

    public String getMelhor_rota() {
        return melhor_rota;
    }

    public void setMelhor_rota(String melhor_rota) {
        this.melhor_rota = melhor_rota;
    }

    public String getNome_contato() {
        return nome_contato;
    }

    public void setNome_contato(String nome_contato) {
        this.nome_contato = nome_contato;
    }

    public String getTelefone() {
        return telefone;
    }

    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    public String getDh_entrega() {
        return dh_entrega;
    }

    public void setDh_entrega(String dh_entrega) {
        this.dh_entrega = dh_entrega;
    }

    public String getImagem_documento() {
        return imagem_documento;
    }

    public void setImagem_documento(String imagem_documento) {
        this.imagem_documento = imagem_documento;
    }

    public String getDh_sincronismo() {
        return dh_sincronismo;
    }

    public void setDh_sincronismo(String dh_sincronismo) {
        this.dh_sincronismo = dh_sincronismo;
    }

}
