package br.feevale.applogistica.database.orm;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MOTORISTA.
 */
public class Motorista {

    private Long id;
    private Long id_web;
    private String nome;
    private String placa;
    private String dh_sincronismo;

    public Motorista() {
    }

    public Motorista(Long id) {
        this.id = id;
    }

    public Motorista(Long id, Long id_web, String nome, String placa, String dh_sincronismo) {
        this.id = id;
        this.id_web = id_web;
        this.nome = nome;
        this.placa = placa;
        this.dh_sincronismo = dh_sincronismo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getId_web() {
        return id_web;
    }

    public void setId_web(Long id_web) {
        this.id_web = id_web;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getPlaca() {
        return placa;
    }

    public void setPlaca(String placa) {
        this.placa = placa;
    }

    public String getDh_sincronismo() {
        return dh_sincronismo;
    }

    public void setDh_sincronismo(String dh_sincronismo) {
        this.dh_sincronismo = dh_sincronismo;
    }

}
