package br.feevale.applogistica.database.orm;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MOTORISTA.
 */
public class Motorista {

    private Long id;
    /** Not-null value. */
    private String nome;
    private java.util.Date dh_sincronismo;

    public Motorista() {
    }

    public Motorista(Long id) {
        this.id = id;
    }

    public Motorista(Long id, String nome, java.util.Date dh_sincronismo) {
        this.id = id;
        this.nome = nome;
        this.dh_sincronismo = dh_sincronismo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getNome() {
        return nome;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNome(String nome) {
        this.nome = nome;
    }

    public java.util.Date getDh_sincronismo() {
        return dh_sincronismo;
    }

    public void setDh_sincronismo(java.util.Date dh_sincronismo) {
        this.dh_sincronismo = dh_sincronismo;
    }

}
